version: '3'

volumes:
  .:
  postgres_data:
  static:

services:
  db_postgres:
    image: postgres
    environment:
      POSTGRES_USER: angel
      POSTGRES_DB: death_star
      POSTGRES_PASSWORD: Angelo31
    volumes:
      - postgres_data:/var/lib/postgresql/data

  death_star:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - death_star
